version:  '3'
services:
  db:
    image: mongo:5
    restart: always
    ports: 
      - 27017:27017
    mem_limit: 1g
    environment:
      MONGODB_DATABASE: nest-pokemon
    volumes:
      - ./mongo:/data/db
    